### ISSUE TITLE
migliorare visibilità timestamp a fianco del player

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/meteotiles#50]
Richiesta da salop: l'istante attuale dev'essere particolarmente visibile.

Oltre all'aumento di dimensione del carattere si potrebbe pensare di formattarlo per migliorare la leggibilità (tipo `YYYY-MM-DD HH:MM`)

**Comment by edigiacomo** [comment]
Fix disponibile nella versione 0.13, appena deployata.
