### ISSUE TITLE
Comportamento nel caso di prodotti con istanti di validità diversi

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/meteotiles#53]
Proposte:

1. Lasciare com'è adesso: l'utente, come dici tu, ha responsabilità nella scelta di dati omogenei e se sceglie dati che non lo sono è conscio dei limiti. 
2. Fare l'intersezione degli istanti per cui ogni prodotto è disponibile: questo però nasconde dati dei prodotti che hanno più istanti
3. Non permettere la selezione di prodotti che non hanno i medesimi istanti di validità - ma questo comporta che il confronto tra due prodotti per istanti di emissione diversi è vietato.

Tutte e tre le soluzioni possono essere corredate da un avviso (e.g. un popup) che avvisa della disomogeneità degli istanti di validità e quindi, a seconda delle soluzioni scelta, potrebbe essere:

1. "Attenzione: i prodotti scelti hanno istanti di validità diversi e quindi, per alcuni istanti, non saranno visualizzati entrambi i prodotti"
2. "Attenzione: i prodotti scelti hanno istanti di validità diversi e quindi saranno mostrati solo gli istanti comuni"
3. "Attenzione: il prodotto non può essere selezionato perché ha istanti di validità diversi da quelli dei prodotti già selezionati"

**Comment by dcesari** [comment]
Non so se sono titolato a votare, ma sceglierei la 1, trattandosi un prodotto per "professionisti".

**Comment by edigiacomo** [comment]
Grazie @dcesari per il feedback! , ma certamente che sei (ben più che) titolato! Coincide peraltro con l'opinione di Andrea S., quindi ho un'ulteriore conferma :)
