### ISSUE TITLE
Navigazione tra singlemap e doublemap

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/meteotiles#55]
Dalla versione 0.14 sono disponibili le due applicazioni single e double map. Questo significa che ognuna ha il suo file HTML (singlepage.html e doublepage.html) ma:

- Non c'è al momento un modo di passare da una pagina all'altra
- L'index.html non c'è più

**Comment by edigiacomo** [comment]
Proposte:

1. Un index.html che contiene un link ad ognuna delle due applicazioni
2. Il file index.html è un link simbolico a singlemap.html e nell'header mettiamo il link all'altra pagina.

**Comment by brancomat** [comment]
Personalmente mi sembra più pulita la soluzione 2 (in generale: landing page su singlepage e link in header vicendevole fra le due modalità)

**Comment by edigiacomo** [comment]
Sono d'accordo. Per ora ho aggiunto index.html (51aaff7) come link simbolico in vista della presentazione di domani, poi appena riesco a fare un menu decente faccio una nuova release.

**Comment by edigiacomo** [comment]
@brancomat nel branch `issue55` trovi la fix. Secondo me a questo punto del prototipo è sufficiente.

**Comment by brancomat** [comment]
Concordo, benissimo!
